### ISSUE TITLE
More attractive homepage

### ISSUE THREAD

**Issue by heinermann** [Quinny/uWindsor-POTW-Leaderboard#1]
Make a more attractive/useful homepage.

**Comment by StephenNu** [comment]
I concur

**Comment by Quinny** [comment]
Do either of you guys have any ideas for things I could add/do for said homepage?

**Comment by heinermann** [comment]
How about a direct link to the current problem of the week?

**Comment by Quinny** [comment]
Updated to show the most recent problem of the week. I played around with a couple things, and i think this is the best option for now
