### ISSUE TITLE
@domain correction

### ISSUE THREAD

**Issue by heinermann** [Quinny/uWindsor-POTW-Leaderboard#11]
If they enter @uwindsor.ca, remove the domain.
If they enter @anything then tell them that they entered an invalid address.

i.e. I can sign up with my @gmail address and it will work.

**Comment by Quinny** [comment]
I think i fixed it.  Can you test and confirm?

**Comment by heinermann** [comment]
If I enter heinerm@uwindsor.ca it still says it's invalid. It should accept @uwindsor.ca still but then remove the domain. It correctly rejects everything else.

**Comment by Quinny** [comment]
It clearly states enter your uWindsor ID so I don't think that is really nessesary
