### ISSUE TITLE
Add an indicator for the current problem of the week

### ISSUE THREAD

**Issue by heinermann** [Quinny/uWindsor-POTW-Leaderboard#14]
We can assume that the latest week is the current problem of the week, but if a new problem hasn't been added, it would be misleading. (For example when people go on vacation)

Perhaps indicating (current) on the current week or something would be appropriate.

**Comment by Quinny** [comment]
I don't understand why this necessary, the highest week number is the latest problem

**Comment by heinermann** [comment]
Yes but will it always 100% be the current problem? If everyone goes on vacation, you're not going to continuously create new problems of the week. Do submissions not close the following week?

**Comment by Quinny** [comment]
It was more of an arbitrary time period this year, usually 1-2 weeks
