### ISSUE TITLE
Student profile customisation

### ISSUE THREAD

**Issue by heinermann** [Quinny/uWindsor-POTW-Leaderboard#3]
Customise student profiles. Potentially request a gravatar image or something.

**Comment by Quinny** [comment]
Profiles have been updated to pull gravatar images based on the uwindsor email.  Any other suggestions in this area?

**Comment by heinermann** [comment]
I can't think of anything ATM regarding profile information without explicitly having them log into an account. Is there a UWindsor login API? I know Gmail and other services use it.

Ideally I would have them be able to link their competitive accounts (Project Euler, UVa, etc.) so that there can be other leaderboards.

In addition, they could specify their level (undergraduate/graduate/F'd off to the industry) so that you can still track and compare against people who are from Windsor.

**Comment by Quinny** [comment]
I was talking to Jordan Willis about a login API.  Until then though, I think this will be it.  I'd rather not fragment their logins by having people create another account on here.
